# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for specific changed files
  push:
    paths: 
      # Change of LaTeX file
      - '**.tex'
      # Change of build config
      - '**.yml'
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up fonts
        run: |
          wget https://github.com/marcologous/Open-Sauce-Fonts/raw/master/fonts/OpenSauceSans-Regular.ttf
          wget https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip
          wget https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf
          unzip Fira_Code_v6.2.zip -d Fira_Code
          mkdir -p "$HOME/.local/share/fonts/"
          cp -r "OpenSauceSans-Regular.ttf" "$HOME/.local/share/fonts/"
          cp -r "NotoColorEmoji.ttf" "$HOME/.local/share/fonts/"
          cp -r "Fira_Code/ttf/FiraCode-Regular.ttf" "$HOME/.local/share/fonts/"
          rm Fira_Code_v6.2.zip
          rm -r Fira_Code
          rm OpenSauceSans-Regular.ttf
          rm NotoColorEmoji.ttf
          
      - name: Install basic TeX-live
        run: |
          wget https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          mkdir tl
          tar -xf install-tl-unx.tar.gz -C tl
          rm install-tl-unx.tar.gz
          cd tl
          mv */* . # Move everything here, so the date-dependent subfolder is not required
          printf "s\nd\nr\nc\nG\nr\ni\n" | sudo perl install-tl
          #s = Scheme
          #d = basic
          #r = return
          #c = Collections
          #G = LuaLaTeX
          #r = return
          #i = Start installation
          cd ..
          rm -r tl
          
      - name: Install packages
        run: |
          sudo /usr/local/texlive/2021/bin/x86_64-linux/tlmgr install preprint xcolor fontspec multirow booktabs makecell adjustbox xkeyval collectbox pgf datetime fmtcount enumitem tcolorbox environ
        
      - name: Compile all tex files
        run: |
          export TEXINPUTS=.:
          find . -name '*.tex' -execdir bash -c 'if ! [[ $PWD = */cornlib ]] ; then /usr/local/texlive/2021/bin/x86_64-linux/lualatex $0; fi;' {} +
          
      - name: Commit changes to master
        run: |
          git config user.email "monsterdruide1@users.noreply.github.com"
          git config user.name "LaTeX-BuildBot"
          git add --all
          git commit -m "[BuildBot] Auto-regenerate 🌽-sheet PDFs"
          git push
          
      # TEXLive basic + lualatex
      # other packages: 
      #   preprint (fullpage.sty), xcolor, fontspec, multirow, booktabs, makecell, adjustbox, xkeyval, collectbox, pgf, datetime, fmtcount, enumitem, tcolorbox, environ
